name: Actividad Diaria Automática

on:
  schedule:
    - cron: '5 21 * * *'
  workflow_dispatch: 

jobs:
  refresh-activity:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4 # <--- Actualizado a v4 para evitar la advertencia

    - name: Modificar el README
      run: |
        echo "Última actualización de actividad: $(date)" > actividad.txt
        echo -e "\n" >> README.md

    - name: Configurar Git y Hacer Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # <--- Esto le da el superpoder de escribir
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "style: actualización automática de estado [skip ci]" || exit 0
        git push
